name: Build and test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      APP_DIRECTORY: app
      GCS_BUCKET_MASTER: ${{ secrets.GCS_BUCKET_MASTER }}
      HEAD_SOME: refs/heads/develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Gos
        # if: github.env.GITHUB_EVENT_NAME == env.HEAD_SOME
        run: echo ${{ env.GITHUB_EVENT_NAME }}

      - name: Go
        if: github.base_ref == env.HEAD_SOME
        run: echo
  deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: HELLO
        # if: github.env.GITHUB_EVENT_NAME == env.HEAD_SOME
        run: echo ${{ github.event_name }}
        # run: echo "-----> ${{ github.head_ref }} | ${{ github.base_ref }} | ${{ github.ref }}""
      # - name: Install dependencies
      #   run: npm install
      # # - name: Lint
      # #   run: npm run lint
      # # - name: Prettier check
      # #   run: npm run prettier-check
      # - name: Build dev
      #   run: npm run build -- --output-path dist --base-href "$GCS_BUCKET_MASTER"
      # # - name: Test
      # #   run: npm run test-single-run
      # - name: "Upload artifact #2"
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app
      #     path: dist
      # - name: Setup - gcloud / gsutil
      #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     service_account_key: ${{ secrets.GCS_SA_KEY_MASTER }}
      #     project_id: ${{ secrets.GCS_PROJECT_MASTER }}
      #     export_default_credentials: true
      # - name: GCLoud info
      #   run: gcloud info
      # - name: Deploy
      #   run: |-
      #     gsutil -m rsync -R dist gs://$GCS_BUCKET_MASTER
  # deploy:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - name: Download math result for job 2
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: app
  #     - name: Print the final result
  #       shell: bash
  #       run: echo ${{hashFiles('index.html')}}
